# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npx eslint index.js
    # - run:npm run build --if-present
    - run: npm test
    - name: Run Cucumber BDD tests
      run: npx cucumber-js

  codeql-analysis:
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1

      - name: Analyze with CodeQL
        uses: github/codeql-action/analyze@v1

      - name: Upload SARIF report
        uses: actions/upload-artifact@v2
        with:
          name: codeql-sarif-report
          path: .codeql/results
